### ISSUE TITLE
User will see statistically signifcant values in font color BLACK, and other insignificant/not available values in GRAY

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#11]
If variable values have no statistical significance, font color will be set to GRAY . Otherwise, font color will be BLACK.

CV > 20
Sig < 1.645

**Comment by andycochran** [comment]
We'll need to add a CV column name for each value in the popup. Something like this: 

```
  popupColumns:
  - id: pop
    title: Population
    large: true
    values:
    - geomType: municipality
      columnName: popa16
      cv: popacv16
```

Then add something like `,${match.cv} AS cv` to the `getPopupValue()` function. 

Then `columnTitles.map` will need to set the `isInsignificant` var to true if > 20 so it can return `${isInsignificant ? 'medium-gray' : ''}` in the `<td>`'s class. 

@chriswhong I've tried ^this in my `feature/75-highlight-current-geog-in-popup` branch, but failed. Maybe we can pair on it?
